Errors at compile time with NS >= 3.17:
  src/Simulator/simulator.cpp:424:18: error: ‘class ns3::PLC_Interference’ has no member named ‘StartRx’
       interference.StartRx(rxPSD);

Solution found:

  Use Initialize() instead of Start().
  See http://code.nsnam.org/ns-3.17/raw-file/96ada8e6b920/CHANGES.html